### ISSUE TITLE
Hypothesmith 0.0.3 Appears Incompatible with Hypothesis above 4.32.3

### ISSUE THREAD

**Issue by DragonMinded** [Zac-HD/hypothesmith#3]
Commit https://github.com/HypothesisWorks/hypothesis/commit/2b7ddefbedfe1d20975576f9bc947c056f936399#diff-a6a0e1e84af3282e1fc162b4ebec8fdf introduced a new required parameter to LarkStrategy in hypothesis, but hypothesmith seems to still initialize without it. A marginally useful stack trace from LibCST is as follows:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.6/unittest/main.py", line 141, in parseArgs
    self.createTests()
  File "/usr/lib/python3.6/unittest/main.py", line 148, in createTests
    self.module)
  File "/usr/lib/python3.6/unittest/loader.py", line 219, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.6/unittest/loader.py", line 219, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/dragonminded/LibCST/libcst/tests/test_fuzz.py", line 49, in <module>
    class FuzzTest(unittest.TestCase):
  File "/home/dragonminded/LibCST/libcst/tests/test_fuzz.py", line 55, in FuzzTest
    @hypothesis.given(source_code=from_grammar(start="file_input"))
  File "/home/dragonminded/LibCST/.tox/fuzz/lib/python3.6/site-packages/hypothesmith/syntactic.py", line 106, in from_grammar
    return GrammarStrategy(grammar, start, explicit_strategies).map(check_and_fix)
  File "/home/dragonminded/LibCST/.tox/fuzz/lib/python3.6/site-packages/hypothesmith/syntactic.py", line 55, in __init__
    LarkStrategy.__init__(self, grammar, start=start)  # type: ignore
TypeError: __init__() missing 1 required positional argument: 'explicit'
```

Pinning to hypothesis 4.32.3 works around the problem.

**Comment by Zac-HD** [comment]
Yep, this is a known issue - actually caused by upstreaming some of the code from Hypothesmith! I've been at EuroSciPy for the last week, but will be updating this end soon 🙂

**Comment by Zac-HD** [comment]
Done!

And as a bonus, while refactoring I tightened up one of the inner filters... so you might find bugs with 0.0.4 that didn't show up before.  I actually had to loosen a test due to a parsing issue in Black 😁

**Comment by DragonMinded** [comment]
Wow, thanks for the super fast response! I'll upgrade our dependencies.
